INSERT INTO administrative_dim WITH(TABLOCK) (
	ADMINCAT
	,ADMINCATST
	,CATEGORY
) (
	SELECT DISTINCT 
		ADMINCAT
		,ADMINCATST
		,CATEGORY
	FROM HES_APC
);

--ALTER TABLE HES_APC ADD ADMINID INT

UPDATE src WITH(TABLOCK) SET
	src.ADMINID = dim.ADMINID
FROM administrative_dim AS dim
JOIN HES_APC AS src
	ON src.ADMINCAT = dim.ADMINCAT
	AND src.ADMINCATST = dim.ADMINCATST
	AND src.CATEGORY = dim.CATEGORY