INSERT INTO provider_dim (
	PROCODE
) (
	SELECT DISTINCT 
		PROCODE
	FROM HES_APC
);

ALTER TABLE HES_APC ADD PROVID INT

UPDATE src SET
	src.PROVID = dim.PROVID
FROM HES_APC AS src
JOIN provider_dim AS dim
	ON src.PROCODE = dim.PROCODE

-- GP DIM
SELECT DISTINCT
	GPPRAC
FROM HES_APC

ALTER TABLE HES_APC ADD PROVID INT


SELECT *
FROM (SELECT DISTINCT
	GPPRAC, PROCODE 
	,COUNT(GPPRAC) OVER (PARTITION BY PROCODE ORDER BY (SELECT 1)) AS cnt
FROM HES_APC) AS t
WHERE cnt >1
AND PROCODE IS NOT NULL
ORDER BY PROCODE, GPPRAC