INSERT INTO provider_dim (
	PROCODE
) (
	SELECT DISTINCT 
		PROCODE
	FROM HES_APC
);

ALTER TABLE HES_APC ADD PROVID INT

UPDATE src SET
	src.PROVID = dim.PROVID
FROM HES_APC AS src
JOIN provider_dim AS dim
	ON src.PROCODE = dim.PROCODE

-- GP DIM
INSERT INTO gp_dim (
	GPPRAC
	,PROVID
) (
	SELECT DISTINCT
		src.GPPRAC
		,src.PROVID
	FROM HES_APC AS src
);

ALTER TABLE HES_APC ADD GPID INT

UPDATE src SET
	src.GPID = dim.GPID
FROM HES_APC AS src
JOIN gp_dim AS dim
	ON src.GPPRAC = dim.GPPRAC
	AND src.PROVID = dim.PROVID

-- hospital dim

CREATE TABLE hospital_dim (
	HOSPID INT PRIMARY KEY IDENTITY NOT NULL
	,PROVID INT REFERENCES provider_dim(PROVID)
	,GEOID INT REFERENCES geography_dim(GEOID)
);