INSERT INTO provider_dim (
	PROCODE
) (
	SELECT DISTINCT 
		PROCODE
	FROM HES_APC
);

ALTER TABLE HES_APC ADD PROVID INT

UPDATE src SET
	src.PROVID = dim.PROVID
FROM HES_APC AS src
JOIN provider_dim AS dim
	ON src.PROCODE = dim.PROCODE