CREATE Table elective_dim
(
ELECTIVEID INT IDENTITY PRIMARY KEY,
ELECDUR INT,
ELECDUR_CALC INT,
DATEID INT 
)

INSERT INTO elective_dim WITH(TABLOCK) (
	ELECDUR
	,ELECDUR_CALC
) (
	SELECT DISTINCT 
		ELECDUR
		,ELECDUR_CALC
	FROM HES_APC
);

--ALTER TABLE HES_APC ADD ELECTIVEID INT

UPDATE src WITH(TABLOCK) SET
	src.ELECTIVEID = dim.ELECTIVEID
FROM HES_APC AS src
JOIN elective_dim AS dim 
	ON src.ELECDUR = dim.ELECDUR
	AND src.ELECDUR_CALC = dim.ELECDUR_CALC


UPDATE elecDIM SET 
	elecDIM.DATEID = dateDIM.DATEID
FROM elective_dim AS elecDIM
JOIN HES_APC
	ON HES_APC.ELECTIVEID = elecDIM.ELECTIVEID
JOIN date_dim AS dateDIM
	ON ELECDATE = [DATE]
JOIN patient_dim AS patDIM
	ON patDIM.HESID = HES_APC.HESID
	AND HES_APC.SEX = patDIM.SEX
	AND HES_APC.ETHNOS = patDIM.ETHNOS
	AND HES_APC.DOB = patDIM.DOB
	AND HES_APC.NEWNHSNO = patDIM.NEWNHSNO
	AND HES_APC.NEWNHSNO_CHECK = patDIM.NEWNHSNO_CHECK
	AND HES_APC.LEGLCAT = patDIM.LEGLCAT



ALTER TABLE elective_dim
	ADD FOREIGN KEY (DATEID) REFERENCES date_dim(DATEID)