
-- NULLS_elective_dim_ELECDATE
BEGIN TRAN NULLS_elective_dim_ELECDATE
UPDATE HES_APC SET
	ELECDATE = ISNULL(ELECDATE, CAST('1800-01-01' AS DATE))
FROM HES_APC
WHERE ELECDATE IS NULL

SELECT ELECDATE FROM HES_APC
WHERE ELECDATE IS NULL
COMMIT TRAN NULLS_elective_dim_ELECDATE
GO

-- NULLS_elective_dim_ELECDATE
BEGIN TRAN NULLS_elective_dim_ELECDATE
UPDATE HES_APC SET
	ENDAGE = 0000
FROM HES_APC
WHERE ENDAGE IS NULL
COMMIT TRAN NULLS_elective_dim_ELECDATE
GO


-- NULLS_admission_dim_BEDYEAR
BEGIN TRAN NULLS_admission_dim_BEDYEAR
UPDATE HES_APC SET
	BEDYEAR = 9999
WHERE BEDYEAR IS NULL
COMMIT TRAN NULLS_admission_dim_BEDYEAR
GO

-- NULLS_admission_dim_LOPATID
BEGIN TRAN NULLS_admission_dim_LOPATID
UPDATE HES_APC SET
	LOPATID = ''
WHERE LOPATID IS NULL
COMMIT TRAN NULLS_admission_dim_LOPATID
GO


-- NULLS_spell_dim_SPELEND
BEGIN TRAN NULLS_spell_dim_SPELEND
UPDATE HES_APC SET
	SPELEND = 'NUL'
WHERE SPELEND IS NULL
ROLLBACK TRAN NULLS_spell_dim_SPELEND

-- NULLS_spell_dim_SPELDUR
BEGIN TRAN NULLS_spell_dim_SPELDUR
UPDATE HES_APC SET
	SPELDUR = -1
WHERE SPELDUR IS NULL
ROLLBACK TRAN NULLS_spell_dim_SPELDUR

