DROP TABLE adm_patient_care_fact

CREATE TABLE adm_patient_care_fact (
	 IDENTIFIER		UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY
	,HESID			NVARCHAR(15)	--REFERENCES patient_dim(HESID)
	,DIAGNOSISID	INT				--REFERENCES diagnosis_dim(DIAGNOSISID)
	,ADMINID		INT				--REFERENCES administrative_dim(ADMINID)
	,ELECTIVEID		INT				--REFERENCES elective_dim(ELECTIVEID)
	,SPELLID		INT				--REFERENCES spell_dim(SPELLID)
	,EPISODEID		INT				--REFERENCES episode_dim(EPISODEID)
	,ADMISID		INT				--REFERENCES admission_dim(ADMISID)
	,PROVID			INT				--REFERENCES provider_dim(PROVID)

	--CONSTRAINT pk_adm_patient_care_fact PRIMARY KEY NONCLUSTERED (
	--	 IDENTIFIER	
	--	,HESID		
	--	,DIAGNOSISID
	--	,ADMINID	
	--	,ELECTIVEID	
	--	,SPELLID	
	--	,EPISODEID	
	--	,ADMISID	
	--	,PROVID		
	--)
	
);

--TRUNCATE TABLE adm_patient_care_fact

INSERT INTO adm_patient_care_fact (
	HESID
	,ELECTIVEID
	,EPISODEID
	,ADMISID
	,DIAGNOSISID
	,ADMINID
	,SPELLID
	,PROVID
) (
	SELECT
		HESID
		,ELECTIVEID
		,EPISODEID
		,ADMISID
		,DIAGNOSISID
		,ADMINID
		,SPELLID
		,PROVID
	FROM HES_APC
	WHERE HESID IN (SELECT HESID FROM patient_dim)
);

ALTER TABLE adm_patient_care_fact ADD 
		FOREIGN KEY (HESID) REFERENCES patient_dim(HESID)
		,FOREIGN KEY (ELECTIVEID) REFERENCES elective_dim(ELECTIVEID)
		,FOREIGN KEY (EPISODEID) REFERENCES  episode_dim(EPISODEID)
		,FOREIGN KEY (ADMISID) REFERENCES  admission_dim(ADMISID)
		,FOREIGN KEY (DIAGNOSISID) REFERENCES  diagnosis_dim(DIAGNOSISID)
		,FOREIGN KEY (ADMINID) REFERENCES  administrative_dim(ADMINID)
		,FOREIGN KEY (SPELLID) REFERENCES  spell_dim(SPELLID)
		,FOREIGN KEY (PROVID) REFERENCES  provider_dim(PROVID)
; 
GO



