--EST_ErrorLog

IF EXISTS (SELECT object_id('TEST_ERRORLOG') FROM sys.tables)
BEGIN
	DROP TABLE TEST_ERRORLOG
END


CREATE TABLE TEST_ERRORLOG (
	ERRORCODE NVARCHAR(20)
	,ERRORCOL NVARCHAR(20)
) ;


-- EST_DIMpatient


IF EXISTS (SELECT object_id('TEST_patient_dim') FROM sys.tables)
BEGIN
	DROP TABLE TEST_patient_dim
END

CREATE TABLE TEST_patient_dim (
	HESID NVARCHAR(15) PRIMARY KEY NOT NULL 
	,SEX NVARCHAR(1) NOT NULL
	,ETHNOS NVARCHAR(3) NULL
	,DOB DATE NOT NULL
	,NEWNHSNO NVARCHAR(15) NULL
	,NEWNHSNO_CHECK NVARCHAR(1) NULL
	,LEGLCAT NVARCHAR(2) NULL
);