
-- NULLS_elective_dim_ELECDATE
BEGIN TRAN NULLS_elective_dim_ELECDATE

UPDATE HES_APC SET
	ELECDATE = ISNULL(ELECDATE, CAST('1800-01-01' AS DATE))
FROM HES_APC
WHERE ELECDATE IS NULL

SELECT ELECDATE FROM HES_APC
WHERE ELECDATE IS NULL

COMMIT TRAN NULLS_elective_dim_ELECDATE