--HEST4-31


ALTER TABLE HES_APC ADD EPISODEID INT

UPDATE src SET
	src.EPISODEID = dim.EPISODEID
FROM HES_APC AS src
JOIN episode_dim AS dim 
	ON src.EPISODE = dim.EPISODE
	AND src.EPIDUR = dim.EPIDUR
	AND src.EPIEND = dim.EPIEND
	AND src.EPISTART = dim.EPISTART
	AND src.EPISTAT  = dim.EPISTAT 
	AND src.EPITYPE	 = dim.EPITYPE	
	AND src.STARTAGE = dim.STARTAGE
	AND src.ENDAGE 	 = dim.ENDAGE 	
	AND src.ACTIVAGE = dim.ACTIVAGE
	AND src.EPIORDER = dim.EPIORDER
	